routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});
//Administrador
Route::get('/Panel-Administrador', function () {
    return view('Administrador.Dashboard');
});

Route::get('/AdminInforme', function () {
    return view('Administrador.Informe');
});

Route::get('/AdminUsuarios','AdminController@usuarios');

Route::get('/AdminDocumentos','AdminController@documentos');


Route::get('/home', function () {
    return view('home');
});

Route::get('/capturaExp', function () {
    return view('expedientes.create');
});

Route::get('/header', function () {
    return view('layouts.header');
});

Route::get('/perfil', function () {
    return view('users.perfil');
});
Route::get('/tutoria', function () {
    return view('pdf.docencia.tutoria');
});

Route::get('/GestionAcademica', function () {
    return view('pdf.academica.gestionAcademica');
});

Route::get('/capacitacion', function () {
    return view('users.capacitacion');
});


// Route::group(['middleware' => ['role:PTC']], function () {
//     Route::get('/Articulo', function () {
//     return view('pdf.academica.articulo');
// });
// });

Route::get('/Articulo-Revista', function () {
    return view('pdf.academica.Articulo_revista');
});
Route::get('/Articulo-Arbitrado', function () {
    return view('pdf.academica.Articulo_Arbitrado');
});

Route::get('/asesorias', function () {
    return view('pdf.academica.Asesorias');
});

Route::get('/Libro', function () {
    return view('pdf.academica.libro');
});

Route::get('/Informe_tec', function () {
    return view('pdf.academica.informe_tec');
});

Route::get('/Proyecto', function () {
    return view('pdf.academica.proyecto');
});

Route::get('/material', function () {
    return view('pdf.academica.Material');
});

Route::get('/curso', function () {
    return view('pdf.docencia.curso');
});

Route::get('/tutoriaGrupal', function () {
    return view('pdf.docencia.tutoria_grupal');
});

Route::get('/direccionIndividualizada', function () {
    return view('pdf.docencia.direccion_individualizada');
});

Route::get('/estadiaEmpresa', function () {
    return view('pdf.docencia.estadia');
});

Route::get('/cuerpoAcademico', function () {
    return view('pdf.docencia.cuerpo_academico');
});

Route::get('/informes', function () {
    return view('supervisor.informe');
});

Route::get('/consultaInfo', function () {
    return view('supervisor.consulta');
});

Route::get('/supervisorDash', function () {
    return view('supervisor.dashboard');
});

//PDF capturaExp
Route::get('/capturaExp', 'PdfController@pdfForm');
Route::post('pdf_download', 'PdfController@pdfDownload');

//PDF Articulo

Route::group(['middleware' => ['role:PTC']], function () {
    Route::get('/articulo', 'PdfController@pdfFormArticulo');
});
Route::post('pdf_download_Articulo', 'PdfController@pdfDownload_Articulo');

//PDF Material
Route::get('/Material', 'PdfController@pdfFormMaterial');
Route::post('pdf_download_Material', 'PdfController@pdfDownload_Material');

//PDF Asesorias
Route::get('/Asesorias', 'PdfController@pdfFormAsesorias');
Route::post('pdf_download_Asesorias', 'PdfController@pdfDownload_Asesorias');

//PDF Proyecto
Route::get('/proyecto', 'PdfController@pdfFormProyecto');
Route::post('pdf_download_Proyecto', 'PdfController@pdfDownload_Proyectos');

//PDF Revista
Route::get('/Articulo_revista', 'PdfController@pdfFormRevista');
Route::post('pdf_download_Revista', 'PdfController@pdfDownload_Revista');

//PDF Arbitrado
Route::get('/Articulo_Arbitrado', 'PdfController@pdfFormArbitrado');
Route::post('pdf_download_Arbitrado', 'PdfController@pdfDownload_Arbitrado');

//PDF Libro
Route::get('/libro', 'PdfController@pdfFormLibro');
Route::post('pdf_download_Libro', 'PdfController@pdfDownload_Libro');

//PDF Informe
Route::get('/informe_tec', 'PdfController@pdfFormInforme');
Route::post('pdf_download_Informe', 'PdfController@pdfDownload_Informe');

Route::post('pdf_download_Curso', 'PdfController@pdfDownload_Curso');

Route::post('pdf_download_Tutoria', 'PdfController@pdfDownload_Tutoria');

Route::post('pdf_download_Grupal', 'PdfController@pdfDownload_Tutoria_Grupal');

Route::post('pdf_download_Direccion_Individualizada', 'PdfController@pdfDownload_Direccion_Individualizada');

Route::post('pdf_download_Estadia_Empresa', 'PdfController@pdfDownload_Estadia');

Route::post('pdf_download_Cuerpo_Academico', 'PdfController@pdfDownload_CuerpoAcademico');

//Home
Route::get('/home','HomeController@index');

//Documentos
Route::get('/files/create','DocumentosController@create');
Route::post('/files','DocumentosController@store');

Route::get('/files','DocumentosController@index');
Route::get('/files/{id}','DocumentosController@show');
Route::get('file/download/{file}','DocumentosController@download');

//Busqueda
Route::get('/search','DocumentosController@search');
Route::get('/Adminsearch','AdminController@Adminsearch');
Route::get('/fechas','DocumentosController@fechas');
Route::get('/fechaActual','DocumentosController@fechaActual');
Route::get('/division','AdminController@PorDivision');
Route::get('/nombre','AdminController@PorNombre');
Route::get('/fechasAdmin','AdminController@fechas');
Route::get('/fechaActualAdmin','AdminController@fechaActual');

//Resources
Route::resource('archivos','DocumentosController');
Route::resource('usuario','UserController');
Route::resource('Administrador','AdminController');

Auth::routes();

app/Http/Controllers/DocumentosController.php
<?php

namespace App\Http\Controllers;

use App\Document;
use App\User;
use Illuminate\Http\Request;

class DocumentosController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function search(Request $request){
        $search = $request->get('search'); 
        $file=Document::where('titulo','like',"%$search%")
            ->orWhere('autor','like',"%$search%")
            ->orWhere('tipo','like',"%$search%")
            ->orWhere('cuatrimestre','like',"%$search%")
            ->orWhere('created_at','like',"%$search%")
           ->where('user_id', auth()->user()->id)->orderBy('id', 'DESC')->get();;

        return view('documentos.index',compact('file'));
    }
  
    public function fechas(Request $request){
        $fechas = $request->get('fechas');      
        $file=Document::where('cuatrimestre','like',"%$fechas%")->where('user_id', auth()->user()->id)->orderBy('id', 'DESC')->get();

        return view('documentos.index',compact('file'));
    }
    public function fechaActual(Request $request){
        $fechaActual = $request->get('fechaActual');      
        $file=Document::where('created_at','like',"%$fechaActual%")->where('user_id', auth()->user()->id)->orderBy('id', 'DESC')->get();

        return view('documentos.index',compact('file'));
    }
       public function index()
    {
        $file = Document::where('user_id', auth()->user()->id)->orderBy('id', 'DESC')->get();
        return view('documentos.index', compact('file'));
    }


    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create(){
        return view('documentos.create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(User $user, Request $request){
        $data = new Document;

        if($request->file('file'))
        {
            $file=$request->file('file');
            $filename=time().'.'.$file->getClientOriginalExtension();
            $request->file->move('storage/' , $filename);

            $data->file=$filename;
        }
        $data->user_id = auth()->id();
        $data->titulo=$request->titulo;
        $data->autor=$request->autor;
        $data->descripcion=$request->descripcion;
        $data->tipo=$request->tipo;
        $data->cuatrimestre=$request->cuatrimestre;
      //  $data->User()->associate($user)->save();
        $data->save();

        return redirect()->route('archivos.index');
    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id){
        $data=Document::find($id);

        return view('documentos.view',compact('data'));
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function download($file){
        return response()->download('storage/' .$file);
    }

    public function edit($id){
    //
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id){
    //
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id){
        $data = Document::find($id);
        $data->delete();

        return redirect()->route('archivos.index');
    }
}

resources/views/documentos/create.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
<div class="panel-header colorut" >
  <div class="page-inner py-5">
    <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
        <div>
            <h2 class="text-black pb-2 fw-bold">Integracion de Expediente</h2>
          </div>		
        </div>
  </div>
  </div>
<div class="page-inner mt--5">	
<div class="row">
          <div class="col-md-12">
              <div class="card">
                  <div class="card-header">
                      <div class="card-title">Subir un archivo </div>
                  </div>
              <div class="card-body">
                
      <form action="/files" method="POST" enctype="multipart/form-data">
     <div class="form-row">
        @csrf 
        <div class="form-group col-md-6 ">  
        <label for="inputEmail4">Titulo del Archivo:</label>
        <input type="text" class="form-control border border-secondary" name="titulo" placeholder="titulo">
      </div>
      <div class="form-group col-md-6 ">
        <label for="inputEmail4">Nombre Del Autor:</label>
        <input type="text" class="form-control border border-secondary" name="autor" placeholder="autor">
      </div>
      <div class="form-group col-md-6">
	                                <label for="inputPassword4">Tipo de Archivo</label>
	                                <select class="custom-select border border-secondary" id="inputGroupSelect01"  name="tipo">
	                                    <option value="Artículo de Asesoría">Artículo de Asesoría</option>
	                                    <option value="Material didáctico">Material didáctico</option>      
                                      <option value="Proyecto de investigación">Proyecto de investigación</option>    
                                      <option value="Captura de Capacitacion">Captura de Capacitacion</option>    
                                      <option value="Artículo de difusión y divulgación">Artículo de difusión y divulgación</option>    
                                      <option value="Artículo en revista">Artículo en revista</option>    
                                      <option value="Capitulo del libro">Capitulo del libro</option>    
                                      <option value="Informe Tecnico">Informe Tecnico</option>    
                                      <option value="Tutoria Individual">Tutoria Individual</option> 
                                      <option value="Tutoria Grupal">Tutoria Grupal</option>    
                                      <option value="Curso">Curso</option>    
                                      <option value="Dirección individualizada">Dirección individualizada</option>
                                      <option value="Estadía en empresas">Estadía en empresas</option> 
                                      <option value="Cuerpo Académico">Cuerpo Académico</option>    
                                      <option value="Gestión Académica">Gestión Académica</option>    
                                      <option value="Capacitación docente">Capacitación docente</option>    
                                	</select>
	                            </div>
                            <div class="form-group col-md-6">
	                                <label for="inputPassword4">Periodo</label>
	                                <select class="custom-select border border-secondary" id="inputGroupSelect01"  name="cuatrimestre">
                                  <option value="Enero-Abril">Enero-Abril</option>
                                  <option value="Mayo-Agosto">Mayo-Agosto</option>     
                                  <option value="Septiembre-Diciembre">Septiembre-Diciembre</option>     
                                  <option value="N/A">N/A</option>  
                                	</select>
	                            </div>
                              <div class="form-group col-md-12">
                                <label for="inputState">Captura de evidencia</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" name="file" id="validatedCustomFile" >
                                    <label class="custom-file-label  border border-secondary" for="validatedCustomFile">Archivo..</label>
                                </div>
                            </div>
                           <input type="submit" class="btn btn-primary" value="Subir Archivo">
      </form>

      @endsection

resources/views/documentos/index.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

<!-- Bootstrap CSS -->
<div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Historial de documentos</h2>
		        </div>		
	        </div>
		</div>
    </div>
    
	<div class="page-inner mt--5">
   			 <div class="container">
             <h4>Buscar Por Año y Periodo</h4>	
             <div class="d-block">
              <!--Filtro Cuatrimestre--->
                  <form action="/fechas" method="GET" class="form-group  col-md-5" style="display: inline-block;" >
                  <div style="display:flex; align-items: baseline;">     
                    <label style="margin-right: 0.2rem;">Cuatrimestre:</label>     
                    <select class="custom-select border border-secondary" id="inputGroupSelect01" style="display: inline-block; margin-right: 0.5rem;" name="fechas">
                                                  <option value="Enero-Abril">Enero-Abril</option>
                                                  <option value="Mayo-Agosto">Mayo-Agosto</option>     
                                                  <option value="Septiembre-Diciembre">Septiembre-Diciembre</option>   
                                              </select> 
                                              
                    <input type="submit"  class="btn btn-default" style="display: inline-block;" value="filtrar">
                    </div>
                </form>
                <!-- Fin de filtro -->
            
            <!--Filtro por año--->
               
                <form action="/fechaActual"  method="GET"  style="display: inline-block;"  class="form-group  col-md-5" >
                <label style="margin-right: 0.2rem;">Año:  
                   <input type="number" class="form-control border border-secondary" style="display: inline-block; margin-right: 0.2rem;" placeholder="filtro por año" min="2017" max="2100" name="fechaActual"> 
                   <input type="submit"  class="btn btn-default"  style="display: inline-block;"value="filtrar"></label>
    </form>
    <!-- Fin de filtro -->
    </div>
                  </div>  
    <div class="container">
        <div class="table-wrapper table-responsive-lg">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                          <table id="dtHorizontalExample" class="table table-striped " >

          <tr>
              <th>#</th>
              <th>Titulo</th>
              <th>Autor</th>
              <th>Tipo de Documento</th>
              <th>Periodo</th>
              <th>Ver</th>
              <th>Descargar</th>
              <th>Fecha de Creacion</th>
              <th>Eliminar</th>
            </tr>
                @foreach ($file as $key=>$data)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$data->titulo}}</td>
                    <td>{{$data->autor}}</td>
                    <td>{{$data->tipo}}</td>
                    <td>{{$data->cuatrimestre}}</td>
                    <td><a class="btn btn-success" href="/files/{{$data->id}}">ver</a></td>
                    <td><a class="btn btn-success" href="/file/download/{{$data->file}}">Descargar</a> </td>
                    <td>{{$data->created_at}}</td>
                    <td>
                        <form action="{{route('archivos.destroy', $data->id)}}"  method="POST"> 
                        @method("DELETE")
                        @csrf
                       <input type="submit" class="btn btn-danger" value="Eliminar">
                       </form>
                    </td>
                    </tr>
                @endforeach
      </table>

      
      @endsection

resources/views/documentos/view.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

      <h2>{{$data->titulo}}</h2>
      <h3>{{$data->autor}}</h3>
      <h3>{{$data->descripcion}}</h3>
      <h1 align='center'>PDF</h1>
      <iframe src="{{url('storage/' .$data->file)}}"  width="100%" height="700px">
      </iframe>
  @endsection
  