routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});
//Administrador
Route::get('/Panel-Administrador', function () {
    return view('Administrador.Dashboard');
});

Route::get('/AdminInforme', function () {
    return view('Administrador.Informe');
});

Route::get('/AdminUsuarios','AdminController@usuarios');

Route::get('/AdminDocumentos','AdminController@documentos');


Route::get('/home', function () {
    return view('home');
});

Route::get('/capturaExp', function () {
    return view('expedientes.create');
});

Route::get('/header', function () {
    return view('layouts.header');
});

Route::get('/perfil', function () {
    return view('users.perfil');
});
Route::get('/tutoria', function () {
    return view('pdf.docencia.tutoria');
});

Route::get('/GestionAcademica', function () {
    return view('pdf.academica.gestionAcademica');
});

Route::get('/capacitacion', function () {
    return view('users.capacitacion');
});


// Route::group(['middleware' => ['role:PTC']], function () {
//     Route::get('/Articulo', function () {
//     return view('pdf.academica.articulo');
// });
// });

Route::get('/Articulo-Revista', function () {
    return view('pdf.academica.Articulo_revista');
});
Route::get('/Articulo-Arbitrado', function () {
    return view('pdf.academica.Articulo_Arbitrado');
});

Route::get('/asesorias', function () {
    return view('pdf.academica.Asesorias');
});

Route::get('/Libro', function () {
    return view('pdf.academica.libro');
});

Route::get('/Informe_tec', function () {
    return view('pdf.academica.informe_tec');
});

Route::get('/Proyecto', function () {
    return view('pdf.academica.proyecto');
});

Route::get('/material', function () {
    return view('pdf.academica.Material');
});

Route::get('/curso', function () {
    return view('pdf.docencia.curso');
});

Route::get('/tutoriaGrupal', function () {
    return view('pdf.docencia.tutoria_grupal');
});

Route::get('/direccionIndividualizada', function () {
    return view('pdf.docencia.direccion_individualizada');
});

Route::get('/estadiaEmpresa', function () {
    return view('pdf.docencia.estadia');
});

Route::get('/cuerpoAcademico', function () {
    return view('pdf.docencia.cuerpo_academico');
});

Route::get('/informes', function () {
    return view('supervisor.informe');
});

Route::get('/consultaInfo', function () {
    return view('supervisor.consulta');
});

Route::get('/supervisorDash', function () {
    return view('supervisor.dashboard');
});

//PDF capturaExp
Route::get('/capturaExp', 'PdfController@pdfForm');
Route::post('pdf_download', 'PdfController@pdfDownload');

//PDF Articulo

Route::group(['middleware' => ['role:PTC']], function () {
    Route::get('/articulo', 'PdfController@pdfFormArticulo');
});
Route::post('pdf_download_Articulo', 'PdfController@pdfDownload_Articulo');

//PDF Material
Route::get('/Material', 'PdfController@pdfFormMaterial');
Route::post('pdf_download_Material', 'PdfController@pdfDownload_Material');

//PDF Asesorias
Route::get('/Asesorias', 'PdfController@pdfFormAsesorias');
Route::post('pdf_download_Asesorias', 'PdfController@pdfDownload_Asesorias');

//PDF Proyecto
Route::get('/proyecto', 'PdfController@pdfFormProyecto');
Route::post('pdf_download_Proyecto', 'PdfController@pdfDownload_Proyectos');

//PDF Revista
Route::get('/Articulo_revista', 'PdfController@pdfFormRevista');
Route::post('pdf_download_Revista', 'PdfController@pdfDownload_Revista');

//PDF Arbitrado
Route::get('/Articulo_Arbitrado', 'PdfController@pdfFormArbitrado');
Route::post('pdf_download_Arbitrado', 'PdfController@pdfDownload_Arbitrado');

//PDF Libro
Route::get('/libro', 'PdfController@pdfFormLibro');
Route::post('pdf_download_Libro', 'PdfController@pdfDownload_Libro');

//PDF Informe
Route::get('/informe_tec', 'PdfController@pdfFormInforme');
Route::post('pdf_download_Informe', 'PdfController@pdfDownload_Informe');

Route::post('pdf_download_Curso', 'PdfController@pdfDownload_Curso');

Route::post('pdf_download_Tutoria', 'PdfController@pdfDownload_Tutoria');

Route::post('pdf_download_Grupal', 'PdfController@pdfDownload_Tutoria_Grupal');

Route::post('pdf_download_Direccion_Individualizada', 'PdfController@pdfDownload_Direccion_Individualizada');

Route::post('pdf_download_Estadia_Empresa', 'PdfController@pdfDownload_Estadia');

Route::post('pdf_download_Cuerpo_Academico', 'PdfController@pdfDownload_CuerpoAcademico');

//Home
Route::get('/home','HomeController@index');

//Documentos
Route::get('/files/create','DocumentosController@create');
Route::post('/files','DocumentosController@store');

Route::get('/files','DocumentosController@index');
Route::get('/files/{id}','DocumentosController@show');
Route::get('file/download/{file}','DocumentosController@download');

//Busqueda
Route::get('/search','DocumentosController@search');
Route::get('/Adminsearch','AdminController@Adminsearch');
Route::get('/fechas','DocumentosController@fechas');
Route::get('/fechaActual','DocumentosController@fechaActual');
Route::get('/division','AdminController@PorDivision');
Route::get('/nombre','AdminController@PorNombre');
Route::get('/fechasAdmin','AdminController@fechas');
Route::get('/fechaActualAdmin','AdminController@fechaActual');

//Resources
Route::resource('archivos','DocumentosController');
Route::resource('usuario','UserController');
Route::resource('Administrador','AdminController');

Auth::routes();

resources/views/Administrador/Dashboard.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
   
<div class="panel-header" style="background: #69bb85;">
        <div class="page-inner py-5">
            <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                <div>
                    <h2 class="text-white pb-2 fw-bold">Dashboard</h2>
                    <h5 class="text-white op-7 mb-2">Sistema Repositorio de Producción Académica</h5>
                </div>
              
            </div>
        </div>
    </div>
    <div class="page-inner mt--5">
    
    <!-- Contenido del Dashboard -->
        <div class="row">
            <!-- Cuadros de menu -->
            <div class="col-md-6 col-xl-6">
                <div class="card p-3 bg-info text-white ">
                    <div class="card-body p-3 text-center">
                        <div class="h1 m-0">
                            <!-- Icono -->
                            <i class="fa fa-user fa-2x"></i>
                        </div>
                        <br>
                        <h1 class="font-bold">{{ auth()->user()->name}}</h1>
                        <h2 class="">Nivel: {{ auth()->user()->programa}}</h2>
                        <h2 class="">Grado de Estudios: {{ auth()->user()->grado}}</h2>
                       </div>
                </div>
            </div>
            <div class="col-md-6 col-xl-6">
                <div class="card p-3 text-white" style="background: #69bb85;">
                    <div class="card-body p-3 text-center text-white ">
                        <div class="h1 m-0">
                            <!-- Icono -->
                            <i class="fa fa-university fa-2x"></i>
                        </div>
                        <br>
                        <h1 class="font-bold">{{ auth()->user()->email}}</h1>
                        <h2 class="">Curp: {{ auth()->user()->curp}}</h2>
                        <h2 class="">RFC: {{ auth()->user()->rfc}}</h2>
                    </div>
                </div>
            </div>
          
        </div>
 <!-- Tabla Documentos -->
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Documentos Almacenados: {{$documents->count()}}</div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-right p-3">
                        <table  class="table table-striped table-responsive" >
                            <tr>
                                <th>#</th>
                                <th>Titulo</th>
                                <th>Autor</th>
                                <th>Ver</th>
                                </tr>
                                @foreach ($documents as $key=>$data)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$data->titulo}}</td>
                                    <td>{{$data->autor}}</td>
                                
                                    <td><a class="btn btn-success" href="/files/{{$data->id}}">ver</a></td>
                                
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
 <!-- Tabla Perfiles Activos -->
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Usuarios Activos: {{$users->count() }}</div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-right p-3">
                        <table  class="table table-striped table-responsive" >
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Role</th>
                                <th>Division</th>
                                </tr>
                                @foreach ($users as $key=>$data)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$data->name}}</td>
                                    <td>{{$data->cat_profesor}}</td>
                                    <td>{{$data->division}}</td>                 
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/Administrador/EditUser.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <br>
        <h1 class="display-4">Actualizacion De Usuario</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('Administrador.update', $data->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="first_name">Nombre:</label>
                <input type="text" class="form-control" name="name" value={{ $data->name }} />
            </div>

            <div class="form-group">
                <label for="last_name">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $data->email }} />
            </div>

            <div class="form-group">
                <label for="email">Division:</label>
                <div >
                               
                                <select class="form-control custom-select" id="inputGroupSelect01"  name="division">
                                    <option value="Económico-Administrativa">Económico-Administrativa</option>
                                    <option value="Gastronomia">Gastronomia</option>
                                    <option value="Turismo">Turismo</option>
                                    <option value="Ingeniería y Tecnología">Ingeniería y Tecnología</option>
                                    </select>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
            </div>
            <div class="form-group">
                <label for="programa">Programa:</label>
                <input type="text" class="form-control" name="programa" value={{ $data->programa }} />
            </div>
            <div class="form-group">
                <label for="sei">SEI:</label>
                <input type="text" class="form-control" name="sei" value={{ $data->sei }} />
            </div>
            <div class="form-group">
                <label for="prodep">PRODEP:</label>
                <input type="text" class="form-control" name="prodep" value={{ $data->prodep }} />
            </div>
            <div class="form-group">
                <label for="prodep">Grado:</label>
                <input type="text" class="form-control" name="grado" value={{ $data->grado }} />
            </div>
            <div class="form-group">
                <label for="curp">CURP:</label>
                <input type="text" class="form-control" name="curp" value={{ $data->curp }} />
            </div>
            <div class="form-group">
                <label for="rfc">RFC:</label>
                <input type="text" class="form-control" name="rfc" value={{ $data->rfc }} />
            </div>
            <div class="form-group">
                <label for="Role">Role:</label>
                <input type="text" class="form-control" name="cat_profesor" value={{ $data->cat_profesor }} />
            </div>
            <div class="form-group">
                <label for="password">Contraseña:</label>
                <input type="text" class="form-control" name="password" value={{ $data->password }} />
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </form>
    </div>
</div>
@endsection

resources/views/Administrador/GestionUsuarios.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')


<!-- Bootstrap CSS -->
<div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Historial de Usuarios</h2>
		        </div>		
	        </div>
		</div>
    </div>
    
	<div class="page-inner mt--5">
   			 <div class="container">
             <h4>Buscar Por Nombre y Division</h4>	
             <div class="d-block">
              <!--Filtro por Division--->
                  <form action="/division" method="GET" class="form-group  col-md-5" style="display: inline-block;" >
                  <div style="display:flex; align-items: baseline;">     
                    <label style="margin-right: 0.2rem;">Division:</label>     
                    <select class="custom-select border border-secondary" id="inputGroupSelect01" style="display: inline-block; margin-right: 0.5rem;" name="division">
                                    <option value="Económico-Administrativa">Económico-Administrativa</option>
                                    <option value="Gastronomia">Gastronomia</option>
                                    <option value="Turismo">Turismo</option>
                                    <option value="Ingeniería y Tecnología">Ingeniería y Tecnología</option>  
                                              </select> 
                                              
                    <input type="submit"  class="btn btn-default" style="display: inline-block;" value="filtrar">
                    </div>
                </form>
                <!-- Fin de filtro -->
            
            <!--Filtro por Nombre--->
               
                <form action="/nombre"  method="GET"  style="display: inline-block;"  class="form-group  col-md-5" >
                <label style="margin-right: 0.2rem;">Nombre:  
                   <input type="text" class="form-control border border-secondary" style="display: inline-block; margin-right: 0.2rem;" placeholder="Nombre" name="nombre"> 
                   <input type="submit"  class="btn btn-default"  style="display: inline-block;"value="filtrar"></label>
    </form>
    <!-- Fin de filtro -->
    </div>
                  </div>  
                  <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Usuarios Activos: {{$users->count() }}</div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-right p-3">
                        <table  class="table table-striped table-responsive" >

          <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Role</th>
              <th>Division</th>
              <th>Datos</th>
              <th>Actualizar Datos</th>
              <th>Eliminar Usuario</th>
             
            </tr>
                @foreach ($users as $key=>$data)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->cat_profesor}}</td>
                    <td>{{$data->division}}</td>
                   
                    <td><a class="btn btn-success" href="{{ route('Administrador.show', $data->id) }}">Ver</a> </td>
                    <td><a class="btn btn-warning" href="{{ route('Administrador.edit', $data->id) }}">Actualizar</a> </td>
                    <td>
                        <form action="{{route('Administrador.destroy', $data->id)}}"  method="POST"> 
                        @method("DELETE")
                        @csrf
                       <input type="submit" class="btn btn-danger" value="Eliminar">
                       </form>
                    </td>
                    </tr>
                @endforeach
      </table>
@endsection

resources/views/Administrador/ViewUser.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

      <h2>{{$data->id}}</h2>
      <h3>{{$data->name}}</h3>
      <h3>{{$data->email}}</h3>
     
  @endsection
  