routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});
//Administrador
Route::get('/Panel-Administrador', function () {
    return view('Administrador.Dashboard');
});

Route::get('/AdminInforme', function () {
    return view('Administrador.Informe');
});

Route::get('/AdminUsuarios','AdminController@usuarios');

Route::get('/AdminDocumentos','AdminController@documentos');


Route::get('/home', function () {
    return view('home');
});

Route::get('/capturaExp', function () {
    return view('expedientes.create');
});

Route::get('/header', function () {
    return view('layouts.header');
});

Route::get('/perfil', function () {
    return view('users.perfil');
});
Route::get('/tutoria', function () {
    return view('pdf.docencia.tutoria');
});

Route::get('/GestionAcademica', function () {
    return view('pdf.academica.gestionAcademica');
});

Route::get('/capacitacion', function () {
    return view('users.capacitacion');
});


// Route::group(['middleware' => ['role:PTC']], function () {
//     Route::get('/Articulo', function () {
//     return view('pdf.academica.articulo');
// });
// });

Route::get('/Articulo-Revista', function () {
    return view('pdf.academica.Articulo_revista');
});
Route::get('/Articulo-Arbitrado', function () {
    return view('pdf.academica.Articulo_Arbitrado');
});

Route::get('/asesorias', function () {
    return view('pdf.academica.Asesorias');
});

Route::get('/Libro', function () {
    return view('pdf.academica.libro');
});

Route::get('/Informe_tec', function () {
    return view('pdf.academica.informe_tec');
});

Route::get('/Proyecto', function () {
    return view('pdf.academica.proyecto');
});

Route::get('/material', function () {
    return view('pdf.academica.Material');
});

Route::get('/curso', function () {
    return view('pdf.docencia.curso');
});

Route::get('/tutoriaGrupal', function () {
    return view('pdf.docencia.tutoria_grupal');
});

Route::get('/direccionIndividualizada', function () {
    return view('pdf.docencia.direccion_individualizada');
});

Route::get('/estadiaEmpresa', function () {
    return view('pdf.docencia.estadia');
});

Route::get('/cuerpoAcademico', function () {
    return view('pdf.docencia.cuerpo_academico');
});

Route::get('/informes', function () {
    return view('supervisor.informe');
});

Route::get('/consultaInfo', function () {
    return view('supervisor.consulta');
});

Route::get('/supervisorDash', function () {
    return view('supervisor.dashboard');
});

//PDF capturaExp
Route::get('/capturaExp', 'PdfController@pdfForm');
Route::post('pdf_download', 'PdfController@pdfDownload');

//PDF Articulo

Route::group(['middleware' => ['role:PTC']], function () {
    Route::get('/articulo', 'PdfController@pdfFormArticulo');
});
Route::post('pdf_download_Articulo', 'PdfController@pdfDownload_Articulo');

//PDF Material
Route::get('/Material', 'PdfController@pdfFormMaterial');
Route::post('pdf_download_Material', 'PdfController@pdfDownload_Material');

//PDF Asesorias
Route::get('/Asesorias', 'PdfController@pdfFormAsesorias');
Route::post('pdf_download_Asesorias', 'PdfController@pdfDownload_Asesorias');

//PDF Proyecto
Route::get('/proyecto', 'PdfController@pdfFormProyecto');
Route::post('pdf_download_Proyecto', 'PdfController@pdfDownload_Proyectos');

//PDF Revista
Route::get('/Articulo_revista', 'PdfController@pdfFormRevista');
Route::post('pdf_download_Revista', 'PdfController@pdfDownload_Revista');

//PDF Arbitrado
Route::get('/Articulo_Arbitrado', 'PdfController@pdfFormArbitrado');
Route::post('pdf_download_Arbitrado', 'PdfController@pdfDownload_Arbitrado');

//PDF Libro
Route::get('/libro', 'PdfController@pdfFormLibro');
Route::post('pdf_download_Libro', 'PdfController@pdfDownload_Libro');

//PDF Informe
Route::get('/informe_tec', 'PdfController@pdfFormInforme');
Route::post('pdf_download_Informe', 'PdfController@pdfDownload_Informe');

Route::post('pdf_download_Curso', 'PdfController@pdfDownload_Curso');

Route::post('pdf_download_Tutoria', 'PdfController@pdfDownload_Tutoria');

Route::post('pdf_download_Grupal', 'PdfController@pdfDownload_Tutoria_Grupal');

Route::post('pdf_download_Direccion_Individualizada', 'PdfController@pdfDownload_Direccion_Individualizada');

Route::post('pdf_download_Estadia_Empresa', 'PdfController@pdfDownload_Estadia');

Route::post('pdf_download_Cuerpo_Academico', 'PdfController@pdfDownload_CuerpoAcademico');

//Home
Route::get('/home','HomeController@index');

//Documentos
Route::get('/files/create','DocumentosController@create');
Route::post('/files','DocumentosController@store');

Route::get('/files','DocumentosController@index');
Route::get('/files/{id}','DocumentosController@show');
Route::get('file/download/{file}','DocumentosController@download');

//Busqueda
Route::get('/search','DocumentosController@search');
Route::get('/Adminsearch','AdminController@Adminsearch');
Route::get('/fechas','DocumentosController@fechas');
Route::get('/fechaActual','DocumentosController@fechaActual');
Route::get('/division','AdminController@PorDivision');
Route::get('/nombre','AdminController@PorNombre');
Route::get('/fechasAdmin','AdminController@fechas');
Route::get('/fechaActualAdmin','AdminController@fechaActual');

//Resources
Route::resource('archivos','DocumentosController');
Route::resource('usuario','UserController');
Route::resource('Administrador','AdminController');

Auth::routes();

app/User.php
<?php

namespace App;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
// use Illuminate\Contracts\Auth\Authenticatable;
// use Illuminate\Auth\Authenticatable as AuthenticableTrait;
// use Illuminate\Notifications\Notifiable;
// use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

use Illuminate\Auth\Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model as Model;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Maklad\Permission\Traits\HasRoles;

class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'email', 
        'division',
        'programa',
        'sei',
        'prodep',
        'grado',
        'curp',
        'rfc',
        'cat_profesor',
        'password',
    ];
    
    public function documents()
{
    return $this->hasMany(Document::class);
}

    public function pdefs()
    {
        return $this->hasMany(Pdef::class);
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.perfil');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function update(Request $request, $id)
    {
        $user =  User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->division = $request->division;
        $user->programa = $request->programa;
        $user->sei = $request->sei;
        $user->prodep = $request->prodep;
        $user->grado = $request->grado; 
        $user->curp = $request->curp;
        $user->rfc = $request->rfc;
        $user->cat_profesor = $request->cat_profesor;
        $user->password = $request->password;
        $user->save(); 
        return redirect()->route('usuario.index')
        ->with('Muy Bien','Sus datos han sido Editados Satisfactoriamente.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
    <div class="panel-header bg-primary-gradient">
        <div class="page-inner py-5">
            <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                <div>
                    <h2 class="text-white pb-2 fw-bold"> Perfil</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="page-inner mt--5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div align="center" class="card-title">Editar perfil</div>
                    </div>                
                    <div class="card-body">
                        <form action="{{ route('usuario.update',auth()->id() ) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Nombre:</strong>
                                        <input type="text" name="name" class="form-control" placeholder="Nombre">
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Correo Electronico:</strong>
                                        <input type="text" name="email" class="form-control" placeholder="Correo Electronico">
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Contraseña:</strong>
                                        <input type="text" name="password" class="form-control" placeholder="Contraseña">
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Division:</strong>
                                        <select class="custom-select" id="inputGroupSelect01"  name="division">
                                            <option value="Económico-Administrativa">Económico-Administrativa</option>
                                            <option value="Gastronomia">Gastronomia</option>
                                            <option value="Turismo">Turismo</option>
                                            <option value="Ingeniería y Tecnología">Ingeniería y Tecnología</option>
                                            </select>
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Programa Educativo:</strong>
                                        <select class="custom-select" id="inputGroupSelect01"  name="programa">
                                            <option value="TSU en Administración área Capital Humano">TSU en Administración área Capital Humano </option>
                                            <option value="TSU en Contaduría">TSU en Contaduría</option>
                                            <option value="TSU en Desarrollo de Negocios área Mercadotecnia">TSU en Desarrollo de Negocios área Mercadotecnia</option>
                                            <option value="TSU en Gastronomía">TSU en Gastronomía</option>
                                            <option value="TSU en Desarrollo de Software Multiplataforma">TSU en Desarrollo de Software Multiplataforma</option>
                                            <option value="TSU en Mantenimiento área Instalaciones">TSU en Mantenimiento área Instalaciones</option>
                                            <option value="TSU en Infraestructura de Redes Digitales">TSU en Infraestructura de Redes Digitales</option>
                                            <option value="TSU en Hotelería">TSU en Hotelería</option>
                                            <option value="TSU en Desarrollo de Productos Alternativos">TSU en Desarrollo de Productos Alternativos</option>
                                            <option value="TSU en Terapia Física">TSU en Terapia Física</option>
                                            <option value="Licenciatura en Gestión del Capital Humano">Licenciatura en Gestión del Capital Humano</option>
                                            <option value="Licenciatura en Innovación de Negocios y Mercadotecnia">Licenciatura en Innovación de Negocios y Mercadotecnia</option>
                                            <option value="Ingeniería Financiera y Fiscal">Ingeniería Financiera y Fiscal</option>
                                            <option value="Licenciatura en Gastronomía">Licenciatura en Gastronomía</option> 
                                            <option value="Ingeniería en Mantenimiento Industrial">Ingeniería en Mantenimiento Industrial</option>
                                            <option value="Ingeniería en Tecnologías de la Información y Comunicación">Ingeniería en Tecnologías de la Información y Comunicación</option>
                                            <option value="Licenciatura en Gestión y Desarrollo Turístico">Licenciatura en Gestión y Desarrollo Turístico</option>      
                                        </select>
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Nivel en el SEI:</strong>
                                        <select class="custom-select" id="inputGroupSelect01"  name="sei">
                                            <option value="Si">Si</option>
                                            <option value="No">No</option>
                                            </select>
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>PRODEP:</strong>
                                        <select class="custom-select" id="inputGroupSelect01"  name="prodep">
                                            <option value="Si">Si</option>
                                            <option value="No">No</option>
                                            </select>
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Grado de Estudios:</strong>
                                        <select class="custom-select" id="inputGroupSelect01"  name="grado">
                                            <option value="Licenciatura">Licenciatura</option>
                                            <option value="Maestría">Maestría</option>
                                            <option value="Licenciatura">Especialidad</option>
                                            <option value="Maestría">Doctorado</option>
                                            </select>
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Curp:</strong>
                                        <input type="text" name="curp" class="form-control" placeholder="Curp">
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>RFC:</strong>
                                        <input type="text" name="rfc" class="form-control" placeholder="RFC">
                                    </div>
                                </div>
                                <div  class="form-group col-md-6">
                                    <div class="form-group">
                                        <strong>Cuerpo Académico:</strong>
                                        <select class="custom-select" id="inputGroupSelect01" name="cat_profesor">
                                            <option value="PTC">PTC</option>
                                            <option value="Coordinador de CAA">Coordinador de CAA</option>
                                            <option value="Coordinador de División">Coordinador de División</option>
                                            <option value="Jefe de departamento de Investigación">Jefe del departamento de Investigación</option>
                                            <option value="Director de División">Director de División</option>
                                            </select>
                                    </div>
                                </div>
                                <div class="col-auto my-3">
                                        <button type="submit" class="btn btn-primary btn-lg active">Enviar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/perfil.blade.php
@extends('layouts.app')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
	<div class="panel-header"  style="background: #69bb85!important; border-color:#69bb85!important;">
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
				<div>
					<h2 class="text-white pb-2 fw-bold"> Perfil</h2>
				</div>
			</div>
		</div>
	</div>
	<div class="page-inner mt--5">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header">
						<div align="center"  class="card-title">Datos personales del usuario</div>
					</div>
					<table class="table table-hover table-dark">                   
						<div class="card text-center">
							<div class="card-body">
								<div class="avatar avatar-xl">
									<img src="../assets/img/profile.jpg" alt="..." class="avatar-img rounded-circle">
								</div>
								<table class="table table-striped table-striped-bg-default mb-3">
							</div>
							<a class="btn btn-primary" style="background: #69bb85!important; border-color:#69bb85!important;"href="{{ route('usuario.edit', auth()->id() ) }}">Editar Datos de Usuario</a>
						<div class="card-footer text-muted">
							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Nombre de  Usuario
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseOne" class="collapse " aria-labelledby="headingOne" data-parent="#accordion">
										<div class="card-body">
											{{ auth()->user()->name }}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Password
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
										<div class="card-body">
											{{ 	 auth()->user()->password }}										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingThree" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											División
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
										<div class="card-body">
											{{ 	 auth()->user()->division }}
										</div>
									</div>
								</div>
							</div>
							<!-- segunda secion -->

							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingfour" data-toggle="collapse" data-target="#collapsefour" aria-expanded="false" aria-controls="collapsefour">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											CURP
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsefour" class="collapse" aria-labelledby="headingfour" data-parent="#accordion">
										<div class="card-body">
											{{ 	 auth()->user()->curp }}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingfive" data-toggle="collapse" data-target="#collapsefive" aria-expanded="false" aria-controls="collapsefive">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											RFC
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsefive" class="collapse" aria-labelledby="headingfive" data-parent="#accordion">
										<div class="card-body">
											{{ 	 auth()->user()->rfc }}
										</div>
									</div>
								</div>
								
							<!-- tercera parte -->
							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingseven" data-toggle="collapse" data-target="#collapseseven" aria-expanded="false" aria-controls="collapseseven">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Programa educativo   
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseseven" class="collapse" aria-labelledby="headingseven" data-parent="#accordion">
										<div class="card-body">
										{{ auth()->user()->programa}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingeight" data-toggle="collapse" data-target="#collapseeight" aria-expanded="false" aria-controls="collapseeight">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Cuerpo Académico
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseeight" class="collapse" aria-labelledby="headingeight" data-parent="#accordion">
										<div class="card-body">
											{{ auth()->user()->cat_profesor}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingnine" data-toggle="collapse" data-target="#collapsenine" aria-expanded="false" aria-controls="collapsenine">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Nivel en el SEI
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsenine" class="collapse" aria-labelledby="headingnine" data-parent="#accordion">
										<div class="card-body">
										{{ auth()->user()->sei}}
										</div>
									</div>
								</div>
							</div>
							<!-- Cuarta parte _-->
							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingten" data-toggle="collapse" data-target="#collapseten" aria-expanded="false" aria-controls="collapseten">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Perfil  PRODEP
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseten" class="collapse" aria-labelledby="headingten" data-parent="#accordion">
										<div class="card-body">
										{{ auth()->user()->prodep}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingeleven" data-toggle="collapse" data-target="#collapseeleven" aria-expanded="false" aria-controls="collapseeleven">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Grado de estudios
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseeleven" class="collapse" aria-labelledby="headingeleven" data-parent="#accordion">
										<div class="card-body">
										{{ auth()->user()->grado}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingtwelve" data-toggle="collapse" data-target="#collapsetwelve" aria-expanded="false" aria-controls="collapsetwelve">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Especialidad
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsetwelve" class="collapse" aria-labelledby="headingtwelve" data-parent="#accordion">
										<div class="card-body">
										{{ auth()->user()->especialidad}}
										</div>
									</div>
								</div>
							</div>
						</div>
					</table>
				</div>
			</div>
		</div>
	</div>
@endsection